# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jesse/cpp/onebuttonRythm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jesse/cpp/onebuttonRythm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/jesse/cpp/onebuttonRythm/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jesse/cpp/onebuttonRythm/CMakeFiles /home/jesse/cpp/onebuttonRythm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jesse/cpp/onebuttonRythm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OneButtonRhythm

# Build rule for target.
OneButtonRhythm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OneButtonRhythm
.PHONY : OneButtonRhythm

# fast build rule for target.
OneButtonRhythm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/build
.PHONY : OneButtonRhythm/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f deps/raylib/raylib/CMakeFiles/raylib.dir/build.make deps/raylib/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f deps/raylib/raylib/external/glfw/src/CMakeFiles/glfw.dir/build.make deps/raylib/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named zip

# Build rule for target.
zip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zip
.PHONY : zip

# fast build rule for target.
zip/fast:
	$(MAKE) $(MAKESILENT) -f deps/zip/CMakeFiles/zip.dir/build.make deps/zip/CMakeFiles/zip.dir/build
.PHONY : zip/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f deps/zip/CMakeFiles/uninstall.dir/build.make deps/zip/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named test_write.out

# Build rule for target.
test_write.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_write.out
.PHONY : test_write.out

# fast build rule for target.
test_write.out/fast:
	$(MAKE) $(MAKESILENT) -f deps/zip/test/CMakeFiles/test_write.out.dir/build.make deps/zip/test/CMakeFiles/test_write.out.dir/build
.PHONY : test_write.out/fast

#=============================================================================
# Target rules for targets named test_append.out

# Build rule for target.
test_append.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_append.out
.PHONY : test_append.out

# fast build rule for target.
test_append.out/fast:
	$(MAKE) $(MAKESILENT) -f deps/zip/test/CMakeFiles/test_append.out.dir/build.make deps/zip/test/CMakeFiles/test_append.out.dir/build
.PHONY : test_append.out/fast

#=============================================================================
# Target rules for targets named test_read.out

# Build rule for target.
test_read.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_read.out
.PHONY : test_read.out

# fast build rule for target.
test_read.out/fast:
	$(MAKE) $(MAKESILENT) -f deps/zip/test/CMakeFiles/test_read.out.dir/build.make deps/zip/test/CMakeFiles/test_read.out.dir/build
.PHONY : test_read.out/fast

#=============================================================================
# Target rules for targets named test_extract.out

# Build rule for target.
test_extract.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_extract.out
.PHONY : test_extract.out

# fast build rule for target.
test_extract.out/fast:
	$(MAKE) $(MAKESILENT) -f deps/zip/test/CMakeFiles/test_extract.out.dir/build.make deps/zip/test/CMakeFiles/test_extract.out.dir/build
.PHONY : test_extract.out/fast

#=============================================================================
# Target rules for targets named test_entry.out

# Build rule for target.
test_entry.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_entry.out
.PHONY : test_entry.out

# fast build rule for target.
test_entry.out/fast:
	$(MAKE) $(MAKESILENT) -f deps/zip/test/CMakeFiles/test_entry.out.dir/build.make deps/zip/test/CMakeFiles/test_entry.out.dir/build
.PHONY : test_entry.out/fast

#=============================================================================
# Target rules for targets named test_permissions.out

# Build rule for target.
test_permissions.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_permissions.out
.PHONY : test_permissions.out

# fast build rule for target.
test_permissions.out/fast:
	$(MAKE) $(MAKESILENT) -f deps/zip/test/CMakeFiles/test_permissions.out.dir/build.make deps/zip/test/CMakeFiles/test_permissions.out.dir/build
.PHONY : test_permissions.out/fast

src/audio.o: src/audio.c.o
.PHONY : src/audio.o

# target to build an object file
src/audio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/audio.c.o
.PHONY : src/audio.c.o

src/audio.i: src/audio.c.i
.PHONY : src/audio.i

# target to preprocess a source file
src/audio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/audio.c.i
.PHONY : src/audio.c.i

src/audio.s: src/audio.c.s
.PHONY : src/audio.s

# target to generate assembly for a file
src/audio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/audio.c.s
.PHONY : src/audio.c.s

src/drawing.o: src/drawing.c.o
.PHONY : src/drawing.o

# target to build an object file
src/drawing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/drawing.c.o
.PHONY : src/drawing.c.o

src/drawing.i: src/drawing.c.i
.PHONY : src/drawing.i

# target to preprocess a source file
src/drawing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/drawing.c.i
.PHONY : src/drawing.c.i

src/drawing.s: src/drawing.c.s
.PHONY : src/drawing.s

# target to generate assembly for a file
src/drawing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/drawing.c.s
.PHONY : src/drawing.c.s

src/files.o: src/files.c.o
.PHONY : src/files.o

# target to build an object file
src/files.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/files.c.o
.PHONY : src/files.c.o

src/files.i: src/files.c.i
.PHONY : src/files.i

# target to preprocess a source file
src/files.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/files.c.i
.PHONY : src/files.c.i

src/files.s: src/files.c.s
.PHONY : src/files.s

# target to generate assembly for a file
src/files.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/files.c.s
.PHONY : src/files.c.s

src/gameplay.o: src/gameplay.c.o
.PHONY : src/gameplay.o

# target to build an object file
src/gameplay.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/gameplay.c.o
.PHONY : src/gameplay.c.o

src/gameplay.i: src/gameplay.c.i
.PHONY : src/gameplay.i

# target to preprocess a source file
src/gameplay.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/gameplay.c.i
.PHONY : src/gameplay.c.i

src/gameplay.s: src/gameplay.c.s
.PHONY : src/gameplay.s

# target to generate assembly for a file
src/gameplay.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/gameplay.c.s
.PHONY : src/gameplay.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/main.c.s
.PHONY : src/main.c.s

src/shared.o: src/shared.c.o
.PHONY : src/shared.o

# target to build an object file
src/shared.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/shared.c.o
.PHONY : src/shared.c.o

src/shared.i: src/shared.c.i
.PHONY : src/shared.i

# target to preprocess a source file
src/shared.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/shared.c.i
.PHONY : src/shared.c.i

src/shared.s: src/shared.c.s
.PHONY : src/shared.s

# target to generate assembly for a file
src/shared.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/shared.c.s
.PHONY : src/shared.c.s

src/thread.o: src/thread.c.o
.PHONY : src/thread.o

# target to build an object file
src/thread.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/thread.c.o
.PHONY : src/thread.c.o

src/thread.i: src/thread.c.i
.PHONY : src/thread.i

# target to preprocess a source file
src/thread.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/thread.c.i
.PHONY : src/thread.c.i

src/thread.s: src/thread.c.s
.PHONY : src/thread.s

# target to generate assembly for a file
src/thread.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OneButtonRhythm.dir/build.make CMakeFiles/OneButtonRhythm.dir/src/thread.c.s
.PHONY : src/thread.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... OneButtonRhythm"
	@echo "... glfw"
	@echo "... raylib"
	@echo "... test_append.out"
	@echo "... test_entry.out"
	@echo "... test_extract.out"
	@echo "... test_permissions.out"
	@echo "... test_read.out"
	@echo "... test_write.out"
	@echo "... zip"
	@echo "... src/audio.o"
	@echo "... src/audio.i"
	@echo "... src/audio.s"
	@echo "... src/drawing.o"
	@echo "... src/drawing.i"
	@echo "... src/drawing.s"
	@echo "... src/files.o"
	@echo "... src/files.i"
	@echo "... src/files.s"
	@echo "... src/gameplay.o"
	@echo "... src/gameplay.i"
	@echo "... src/gameplay.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/shared.o"
	@echo "... src/shared.i"
	@echo "... src/shared.s"
	@echo "... src/thread.o"
	@echo "... src/thread.i"
	@echo "... src/thread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

